### ISSUE TITLE
tab completion not working on osx 10.11.1

### ISSUE THREAD

**Issue by kputland** [mrichar1/shellac#1]
I like the idea, however tab completion is not working.
Also sub commands don't seem to work
Session from your example file

```
(myShellac) ?
*** Unknown syntax: ?
(myShellac) help
Documentation about myShellac
(myShellac) alpha
*** Unknown syntax: alpha
(myShellac) help alpha
help_alpha 
(myShellac) help alpha foo
help_alpha foo
(myShellac) alpha bravo
*** Unknown syntax: alpha bravo
(myShellac) alpha
*** Unknown syntax: alpha
(myShellac) bravo
*** Unknown syntax: bravo
(myShellac) delta
*** Unknown syntax: delta
(myShellac) help delta
delta docstring
```

**Comment by mrichar1** [comment]
Thanks for trying out shellac!

I've not touched the example script for ages, and looking at it now, I see it's more like a poor test-suite for my own use than a good demo script to give a feel for how shellac should work.

At present, many of the commands and sub-commands are dead-ends - however some should work - e.g.

```
(myShellac) alpha bravo charlie Hello
Charlie says Hello
```

```
(myShellac) delta run
delta ran
```

Please let me know if these work as shown above?

I'll try to put some work into re-writing the example file to match the documentation in the README, so it's less confusing for anyone trying out this module.

Tab-completion: looking at https://pypi.python.org/pypi/readline it implies that OSX doesn't ship with GNU readline, which is probably where the problem arises.

Could you try installing this pypi readline module and trying the tab-completion again? (This also reminds me I need to push shellac into pypi for easier use!)

I'll try to get hold of an OSX and Windows computers to test shellac on, since I've only been developing on Linux up until now.

**Comment by mrichar1** [comment]
I've (quickly) patched setup.py to hopefully request an appropriate 3rd-party readline library for OSX and Windows, and pushed shellac to pypi to make install/testing easier.

I've also reworked shellac-example.py to be a bit easier to follow as a 'first look' and give more of a real-world feel.

Can you try installing shellac via pypi: `pip install shellac` and then running shellac-example.py again and seeing if tab-completion works, and that the new example behaves as expected?

Thanks!

**Comment by mrichar1** [comment]
Assuming this issue is resolved by the changes detailed above.
